/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafetyMapRouteImport } from './routes/safety-map'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SafetyMapRoute = SafetyMapRouteImport.update({
  id: '/safety-map',
  path: '/safety-map',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/features': typeof FeaturesRoute
  '/safety-map': typeof SafetyMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/features': typeof FeaturesRoute
  '/safety-map': typeof SafetyMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/features': typeof FeaturesRoute
  '/safety-map': typeof SafetyMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/emergency'
    | '/features'
    | '/safety-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/emergency'
    | '/features'
    | '/safety-map'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/emergency'
    | '/features'
    | '/safety-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EmergencyRoute: typeof EmergencyRoute
  FeaturesRoute: typeof FeaturesRoute
  SafetyMapRoute: typeof SafetyMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safety-map': {
      id: '/safety-map'
      path: '/safety-map'
      fullPath: '/safety-map'
      preLoaderRoute: typeof SafetyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EmergencyRoute: EmergencyRoute,
  FeaturesRoute: FeaturesRoute,
  SafetyMapRoute: SafetyMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
